// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace UPCarouselFlowLayout.Sample
{
	public partial class CarouselCollectionViewCell : UICollectionViewCell
	{
		public CarouselCollectionViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
