// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace UPCarouselFlowLayout.Sample
{
    public partial class GradientView : UIView
    {
        public GradientView(IntPtr handle) : base(handle)
        {
        }

        public override void Draw(CGRect rect)
        {
            var colorSpace = CGColorSpace.CreateDeviceRGB();
            var context = UIGraphics.GetCurrentContext();
            context.SaveState();

            var startColor = UIColor.FromRGBA(79f / 255f, 30f / 255f, 122f / 255f, 1f);
            var endColor = UIColor.FromRGBA(46f / 255f, 12f / 255f, 80f / 255f, 1f);
            var colors = new[] {startColor.CGColor, endColor.CGColor};
            var locations = new nfloat[] {0, 1};
            var gradient = new CGGradient(colorSpace, colors, locations);

            var startPoint = new CGPoint(rect.GetMidX(), rect.GetMinY());
            var endPoint = new CGPoint(rect.GetMidX(), rect.GetMaxY());

            context.DrawLinearGradient(gradient, startPoint, endPoint, CGGradientDrawingOptions.None);
            context.RestoreState();
        }
    }
}